services:
  - type: web
    name: tespet-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements-render.txt
    startCommand: bash start.sh
    envVars:
      - key: NVIDIA_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: HF_REPO_ID
        sync: false
      - key: PORT
        value: 10000
